class UserCheckError(Exception):
    pass


class NoReasonRegisteredError(UserCheckError):
    pass
